#!/usr/bin/env python3
"""Extract the M&M core rulebook PDF into one plain-text file per page.

Why this exists: reading a PDF with the agent's ``Read`` tool renders each page
as an *image* — roughly 2k tokens a page — so hunting a rule through a ~250-page
book that way is ruinously expensive. Extracting the text once turns every later
lookup into a cheap ``grep``.

The output is one file per page, zero-padded::

    reference/core-book/p0001.txt ... reference/core-book/pNNNN.txt

so a grep hit's *filename is the page number* — no separate index to consult,
and reading a single page back costs a few hundred tokens.

Usage (from the repo root)::

    python .claude/skills/rulebook/extract.py
    python .claude/skills/rulebook/extract.py path/to/other.pdf

Re-running is safe: the output directory is rebuilt from scratch, so a shorter
book cannot leave stale pages behind. Everything under ``reference/`` is
gitignored — the book is a private local reference, never committed.

Requires ``pdftotext`` (poppler) on PATH; Git for Windows ships it in
``/mingw64/bin``. No Python dependencies beyond the stdlib.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

# Below this many characters per page on average, the PDF almost certainly has
# no text layer (a scan of the book rather than a digital copy).
MIN_CHARS_PER_PAGE = 500

# How many opening pages to preview, so the printed-page offset can be eyeballed.
PREVIEW_PAGES = 15


def find_repo_root(start: Path) -> Path:
    """Walk up from *start* to the repo root (has pyproject.toml + the package)."""
    for d in (start, *start.parents):
        if (d / "pyproject.toml").exists() and (d / "src" / "mm_companion").is_dir():
            return d
    raise SystemExit(f"!! Could not find the repo root above {start}")


def run_pdftotext(pdf: Path) -> str:
    """Return the whole PDF as text, pages separated by form feeds.

    ``-layout`` is not optional: it preserves column alignment, and this book is
    largely tables. Without it, table rows collapse into unreadable prose.
    """
    if shutil.which("pdftotext") is None:
        raise SystemExit(
            "!! pdftotext is not on PATH.\n"
            "   It ships with Git for Windows at /mingw64/bin/pdftotext, and with\n"
            "   the poppler-utils package on Linux."
        )
    result = subprocess.run(
        ["pdftotext", "-layout", "-enc", "UTF-8", str(pdf), "-"],
        capture_output=True,
    )
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace").strip()
        raise SystemExit(f"!! pdftotext failed on {pdf}:\n{stderr}")
    return result.stdout.decode("utf-8", errors="replace")


def split_pages(text: str) -> list[str]:
    """Split pdftotext output on its form-feed page separator."""
    pages = text.split("\f")
    # pdftotext emits a trailing form feed after the last page.
    if pages and not pages[-1].strip():
        pages.pop()
    return pages


def write_pages(out_dir: Path, pages: list[str]) -> None:
    """Rebuild *out_dir* with one ``pNNNN.txt`` per page."""
    for stale in out_dir.glob("p[0-9]*.txt"):
        stale.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)
    for number, page in enumerate(pages, start=1):
        path = out_dir / f"p{number:04d}.txt"
        path.write_text(page.strip("\n") + "\n", encoding="utf-8", newline="\n")


def write_index(out_dir: Path, pdf: Path, pages: list[str]) -> Path:
    """Write a starter INDEX.md recording the extraction and the page offset."""
    index = out_dir / "INDEX.md"
    body = f"""# {pdf.name} — extracted text index

Generated by `.claude/skills/rulebook/extract.py` on {date.today().isoformat()}.
Do not edit the `pNNNN.txt` files; re-run the script instead.

- **Source:** `{pdf.as_posix()}` ({pdf.stat().st_size / (1024 * 1024):.2f} MB)
- **Pages:** {len(pages)} (`p0001.txt` … `p{len(pages):04d}.txt`)

## Printed-page offset

The file name is the **PDF** page. The number printed on the page differs by the
front matter (cover, credits, contents). Fill this in once, by eye, from the
preview the script prints:

    printed page = PDF page - OFFSET     (OFFSET = ?)

## Chapter map

Fill in as chapters are found, so a topic can be narrowed before grepping:

| Chapter | PDF pages |
| --- | --- |
| | |
"""
    index.write_text(body, encoding="utf-8", newline="\n")
    return index


def preview(pages: list[str], count: int) -> None:
    """Print the first meaningful line of the opening pages.

    This is how the printed-page offset gets established: find the page whose
    text says "Chapter 1" or shows printed page 1, and compare it to its PDF
    page number. Auto-detecting footer numbering is fragile, and this is a
    one-time, thirty-second job by eye.
    """
    print(f"\nFirst line of the opening {min(count, len(pages))} pages:")
    for number, page in enumerate(pages[:count], start=1):
        lines = [line.strip() for line in page.splitlines() if line.strip()]
        first = lines[0][:70] if lines else "(blank - likely art or a scan)"
        print(f"  p{number:04d}  {first}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "pdf",
        nargs="?",
        help="PDF to extract (default: reference/core-book.pdf under the repo root)",
    )
    args = parser.parse_args()

    repo_root = find_repo_root(Path(__file__).resolve())
    pdf = Path(args.pdf).resolve() if args.pdf else repo_root / "reference" / "core-book.pdf"
    if not pdf.exists():
        raise SystemExit(
            f"!! {pdf} not found.\n"
            f"   Drop your own copy of the core rulebook there and re-run.\n"
            f"   Everything under reference/ is gitignored."
        )

    out_dir = repo_root / "reference" / pdf.stem
    print(f"Extracting {pdf.name} -> {out_dir.relative_to(repo_root).as_posix()}/ ...")

    pages = split_pages(run_pdftotext(pdf))
    if not pages:
        raise SystemExit(f"!! pdftotext returned no pages for {pdf}.")

    write_pages(out_dir, pages)
    index = write_index(out_dir, pdf, pages)

    total_chars = sum(len(page) for page in pages)
    per_page = total_chars / len(pages)
    size = f"{total_chars / 1024:.0f} KiB"
    print(f"Wrote {len(pages)} pages, {size} of text ({per_page:.0f} chars/page).")
    print(f"Wrote {index.relative_to(repo_root).as_posix()} - record the page offset there.")

    if per_page < MIN_CHARS_PER_PAGE:
        sys.stdout.flush()
        print(
            "\n!! WARNING: barely any text came out. This PDF probably has no text\n"
            "   layer (a scan rather than a digital copy), so grepping it will\n"
            "   silently find nothing. Reading the PDF pages as images is then the\n"
            "   only option, and that is the expensive path this script exists to\n"
            "   avoid, so check with the user before taking it.",
            file=sys.stderr,
        )

    preview(pages, PREVIEW_PAGES)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
